name: PR-CI

on:
  pull_request:
    branches:
      - main
      - v*
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Install
        run: |
          pip install ruff
      - name: Ruff check
        run: |
          ruff check
  spell:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Install
        run: |
          pip install typos
      - name: Typos check
        run: |
          typos
  copyright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: check
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}:pr_branch --depth=1
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          git checkout pr_branch
          git diff --name-only origin/${{ github.event.pull_request.base.ref }} | python3 scripts/copyright.py check